export default function WikiPage({ wiki, wikis }: any): JSX.Element {
  return (
    <>
      <Head>
        <title>Prosperity | {wiki.title}</title>
        <meta name="description" content={wiki.description} />
        <meta name="author" content={wiki.authors} />
      </Head>

      <div className="md:grid md:grid-flow-col content-center gap-8 mx-auto">
        {/* Wiki page navigation
        Contains a list of links to all generated wiki pages.
        When screen is `md` navigation will display as a col next to the wiki contnet.
        When screen is `sm` navigation will display as a row above the wiki content. */}
        <div className="md:order-last">
          <div className="md:float-right md:text-right mb-8 leading-loose">
            {wikis.map(({ title, slug, category }: any) => (
              <div key={title}>
                {category === "generic" && (
                  <>
                    <Link href={`/wiki/${slug}`}>
                      <a className="hover:text-white text-gray-50 no-underline duration-150">
                        {title}
                      </a>
                    </Link>
                    <br />
                  </>
                )}
              </div>
            ))}
            <p className="text-white text-lg my-2">Administration</p>
            {wikis.map(({ title, slug, category }: any) => (
              <div key={title}>
                {category === "admin" && (
                  <>
                    <Link href={`/wiki/${slug}`}>
                      <a className="hover:text-white text-gray-50 no-underline duration-150">
                        {title}
                      </a>
                    </Link>
                    <br />
                  </>
                )}
              </div>
            ))}
            <p className="text-white text-lg my-2">Information</p>
            {wikis.map(({ title, slug, category }: any) => (
              <div key={title}>
                {category === "info" && (
                  <>
                    <Link href={`/wiki/${slug}`}>
                      <a className="hover:text-white text-gray-50 no-underline duration-150">
                        {title}
                      </a>
                    </Link>
                    <br />
                  </>
                )}
              </div>
            ))}
            <p className="text-white text-lg my-2">Guides</p>
            {wikis.map(({ title, slug, category }: any) => (
              <div key={title}>
                {category === "guide" && (
                  <>
                    <Link href={`/wiki/${slug}`}>
                      <a className="hover:text-white text-gray-50 no-underline duration-150">
                        {title}
                      </a>
                    </Link>
                    <br />
                  </>
                )}
              </div>
            ))}
          </div>
        </div>
        {/* Wiki content 
          Contains all content generated by the `ReactMarkdown` component. */}
        <div className="mb-48">
          <p className="text-6xl">{wiki.title}</p>
          <div className="flex content-center gap-8 my-4 text-sm">
            {wiki.authors && (
              <span className="flex content-center gap-2 text-sm">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="self-center w-4 h-4"
                  viewBox="0 0 20 20"
                  fill="currentColor"
                >
                  <path
                    fillRule="evenodd"
                    d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z"
                    clipRule="evenodd"
                  />
                </svg>
                <p>
                  <b>Authors:</b> {wiki.authors}
                </p>
              </span>
            )}
          </div>
          {!wiki.authors && <div className="my-4" />}
          <Format>{wiki.body.raw}</Format>
        </div>
      </div>
    </>
  );
}

export async function getStaticPaths() {
  const paths = allWikis.map((_) => `/wiki/${_._raw.flattenedPath}`);
  return {
    paths,
    fallback: false,
  };
}

// Import wiki content and metadata.
export async function getStaticProps({ params }: any) {
  // Return specific wiki from value passed by slug.
  const wiki = allWikis.find((_) => _._raw.flattenedPath === params.slug);
  // Return all wikis for sidebar navigation.
  const wikis = allWikis
    .map((wiki) => ({
      slug: wiki._raw.flattenedPath,
      title: wiki.title,
      description: wiki.description,
      category: wiki.category,
    }))
    .sort();

  return {
    props: {
      wiki,
      wikis,
    },
  };
}

import Head from "next/head";
import Link from "next/link";
import Format from "@components/format";
import { allWikis } from ".contentlayer/data";
